### ISSUE TITLE
use ruby-install for ITC-2 workflow?

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_validator#163]
The itc-3 and ec-2 uses the workflow action ruby-install to install Ruby and gems on windows:

```yaml
    - name: Install Ruby and gems
      uses: ruby/setup-ruby@v1
      env:
        ImageOS: win19
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems
```

But the itc-2, which runs in Linux, install gems manually, and does not install ruby, so apparently uses a system ruby:

```yaml
    - name: Configure bundle
      run: bundle config set path '~/rsmp_gems/bundle'

    - name: Run bundle install
      run: bundle install
```

Is there are particular reason why ruby-install is not used on Linux/ITC-2? The documentation states that it should work on self-hosted runners, if the system is similar to the hosted runners.

https://github.com/ruby/setup-ruby
