### ISSUE TITLE
Startup sequence spec 3.1.5 violation?

### ISSUE THREAD

**Issue by melihercan** [rsmp-nordic/rsmp_validator#172]
According to `spec 3.1.5`, `Section 5.3.2  5.3.2 Communication establishment between sites and supervision system` the startup sequence should be:
```
1. Site sends RSMP / SXL version (according to section RSMP/SXL Version).
2. The supervision system veries the RSMP version, SXL version and site id. If there is a mismatch
the sequence does not proceed. The system responds with a MessageNotAck and closes the connection
(see section Message acknowledgement)
3. The supervision system sends RSMP / SXL version (according to section RSMP/SXL Version).
RSMP Specication Release 3.1.5 9
4. The site veries the RSMP version, SXL version and site id. If there is a mismatch the sequence does
not proceed. The site responds with a MessageNotAck and closes the connection. (see section Message
acknowledgement)
5. The site sends a Watchdog (according to section Watchdog)
6. The system sends a Watchdog (according to section Watchdog)
....
```

During my validation tests, I observed that this sequence is violated by inserting a sequence right after Site sends the Watchdog. 
For example in `clock_spec.rb` test, `StatusRequest` is injected before the Watchdog from Supervisor as shown below. Any yet, if you ignore it, the test fails. 
I see similar pattern in other tests and I wonder if there is any explanation for this behavior.

[2022-03-23 16:22:10:659] [DBG] [Rsmp.Services.RsmpTransportClientStateMachine] <<<< OUT
{"mType":"rSMsg","type":"Version","mId":"9f070c28-eb3d-4c64-aa7d-73fc3bd969f4","RSMP":[{"vers":"3.1.5"}],"siteId":[{"sId":"Xxx"}],"SXL":"1.0.15"}

[2022-03-23 16:22:10:693] [DBG] [Rsmp.Services.RsmpTransportClientStateMachine] >>>> IN
{"mType":"rSMsg","type":"MessageAck","oMId":"9f070c28-eb3d-4c64-aa7d-73fc3bd969f4"}

[2022-03-23 16:22:10:704] [DBG] [Rsmp.Services.RsmpTransportClientStateMachine] >>>> IN
{"mType":"rSMsg","type":"Version","RSMP":[{"vers":"3.1.5"}],"siteId":[{"sId":"Xxx"}],"SXL":"1.0.15","mId":"353a5a6e-3af9-4f69-8221-e04745c4deae"}

[2022-03-23 16:22:10:708] [DBG] [Rsmp.Services.RsmpTransportClientStateMachine] <<<< OUT
{"mType":"rSMsg","type":"MessageAck","oMId":"353a5a6e-3af9-4f69-8221-e04745c4deae"}

[2022-03-23 16:22:10:725] [DBG] [Rsmp.Services.RsmpTransportClientStateMachine] <<<< OUT
{"mType":"rSMsg","type":"Watchdog","mId":"9e16fcc9-0165-491d-bce6-2629561fbf07","wTs":"2022-03-23T13:22:10.715Z"}

**_[2022-03-23 16:22:10:767] [DBG] [Rsmp.Services.RsmpTransportClientStateMachine] >>>> IN
{"mType":"rSMsg","type":"StatusRequest","ntsOId":"","xNId":"","cId":"TC","sS":[{"sCI":"S0096","n":"year"},{"sCI":"S0096","n":"month"},{"sCI":"S0096","n":"day"},{"sCI":"S0096","n":"hour"},{"sCI":"S0096","n":"minute"},{"sCI":"S0096","n":"second"}],"mId":"cdfb5e52-c575-4d0e-a5af-b6baf8131730"}_**

[2022-03-23 16:22:10:772] [DBG] [Rsmp.Services.RsmpTransportClientStateMachine] >>>> IN
{"mType":"rSMsg","type":"MessageAck","oMId":"9e16fcc9-0165-491d-bce6-2629561fbf07"}

[2022-03-23 16:22:10:774] [DBG] [Rsmp.Services.RsmpTransportClientStateMachine] >>>> IN
{"mType":"rSMsg","type":"Watchdog","wTs":"2022-03-23T13:22:10.771Z","mId":"7754e234-5446-4d77-8e55-3fa60a146984"}

[2022-03-23 16:22:10:777] [DBG] [Rsmp.Services.RsmpTransportClientStateMachine] <<<< OUT
{"mType":"rSMsg","type":"MessageAck","oMId":"7754e234-5446-4d77-8e55-3fa60a146984"}

**Comment by melihercan** [comment]
Here is the part from validator:
```
Failures:

  1) Site::Traffic Light Controller Clock can be read with S0096
     Failure/Error: raise @error if @error

     RSMP::TimeoutError:
       Status response collection in response to cdfb5e52-c575-4d0e-a5af-b6baf8131730 didn't complete within 1s, reached 0/
     # C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rsmp-0.9.1/lib/rsmp/collect/collector.rb:87:in `ok!'
     # C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rsmp-0.9.1/lib/rsmp/proxy.rb:638:in `block in send_and_optionally_collect'
     # C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/async-1.29.2/lib/async/task.rb:260:in `block in make_fiber'
     #
     #   Showing full backtrace because every line was filtered out.
     #   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
     #   RSpec::Configuration#backtrace_inclusion_patterns for more information.
```

**Comment by emiltin** [comment]
Hi @melihercan, thank you very much for reporting this. I need to look a bit more into it, but in first look I agree with you that it looks like the validator is too quick to send the StatusRequest, and should instead way until the watchdog has been send to the site.

**Comment by emiltin** [comment]
The rmsp gem (which handles rsmp communication) has been updated, so that the handshake sequence is not marked as complete until the watchdog messeges  in both directions have been exchanged and acknowledged.
This should ensure that the validator does not send e.g. a status request too early.

Does this work for you?

**Comment by melihercan** [comment]
Here is my tlc.yaml file content:

```
# Config for testing a site running on localhost (e.g. from the rsmp gem)
# The settings are used for starting a local supervisor listening for the site tested
port: 13111
ips: all
rsmp_versions: [3.1.5]
sxl: tlc
intervals:
  timer: 1
  watchdog: 10
timeouts:
  watchdog: 1
  acknowledgement: 1
  connect: 10
  ready: 3
  status_response: 1
  status_update: 1
  subscribe: 1
  command: 1
  command_response: 1
  alarm: 1
  disconnect: 1
  shutdown: 1
  startup_sequence: 5
components:
  main:
    TC:
  signal_group:
    A1:
    A2:
    B1:
    B2:
  detector_logic:
    DL1:
items:
  plans: [1,2]
  traffic_situations: [1,2]
  emergency_routes: [1]
  inputs: [1]
  force_input: 5
restrict_testing:       # restrict what tests are run, default is to run all
  core_version: 3.1.5   # skip unless relevant for core 3.1.5
  sxl_version: 1.0.15   # skip unless relevant for sxl 1.0.15
startup_sequence: 'efg'
secrets:
  security_codes:
    1: '1111'
    2: '2222'
```
