### ISSUE TITLE
signal_plans_spec.rb schema validation fails for 13 individual tests

### ISSUE THREAD

**Issue by sveitech** [rsmp-nordic/rsmp_validator#217]
```

   1) RSMP::SchemaError
      Could not send statusrequest because schema validation failed: /ss/0/sci, enum, {"mtype":"rsmsg","type":"statusrequest","cid":"kk+ag9998=001tc000","ss":[{"sci":"s0022","n":"status"}],"mid":"24554b1e-a86f-415c-8223-779681e05fc6","ntsoid":"","xnid":""}

   2) RSMP::SchemaError
      Could not send statusrequest because schema validation failed: /ss/0/sci, enum, {"mtype":"rsmsg","type":"statusrequest","cid":"kk+ag9998=001tc000","ss":[{"sci":"s0026","n":"status"}],"mid":"5f5d7caa-042a-41c4-9fbb-41e98e70d9c0","ntsoid":"","xnid":""}

   3) RSMP::SchemaError
      Could not send commandrequest because schema validation failed: /arg/0/cci, enum, , /arg/1/cci, enum, {"mtype":"rsmsg","type":"commandrequest","cid":"kk+ag9998=001tc000","arg":[{"cci":"m0016","co":"setweektable","n":"securitycode","v":"testcode2"},{"cci":"m0016","co":"setweektable","n":"status","v":"0-1,6-2"}],"mid":"32dfcd91-eecf-4ca2-ad2f-f4611c0016b1","ntsoid":"","xnid":""}

   4) RSMP::SchemaError
      Could not send statusrequest because schema validation failed: /ss/0/sci, enum, {"mtype":"rsmsg","type":"statusrequest","cid":"kk+ag9998=001tc000","ss":[{"sci":"s0027","n":"status"}],"mid":"3b66edf1-113d-48a7-80eb-9fc67ceb8893","ntsoid":"","xnid":""}

   5) RSMP::SchemaError
      Could not send commandrequest because schema validation failed: /arg/0/cci, enum, , /arg/1/cci, enum, {"mtype":"rsmsg","type":"commandrequest","cid":"kk+ag9998=001tc000","arg":[{"cci":"m0017","co":"settimetable","n":"securitycode","v":"testcode2"},{"cci":"m0017","co":"settimetable","n":"status","v":"12-1-12-59,1-0-23-12"}],"mid":"1a819bbb-7bf3-4143-8a6c-6cc1de44211d","ntsoid":"","xnid":""}

   6) RSMP::SchemaError
      Could not send commandrequest because schema validation failed: /arg/0/cci, enum, , /arg/1/cci, enum, , /arg/2/cci, enum, {"mtype":"rsmsg","type":"commandrequest","cid":"kk+ag9998=001tc000","arg":[{"cci":"m0018","co":"setcycletime","n":"securitycode","v":"testcode2"},{"cci":"m0018","co":"setcycletime","n":"status","v":"5"},{"cci":"m0018","co":"setcycletime","n":"plan","v":"0"}],"mid":"599fb15e-6ed2-4207-a832-ca6acb6832ce","ntsoid":"","xnid":""}

   7) RSMP::SchemaError
      Could not send statusrequest because schema validation failed: /ss/0/sci, enum, {"mtype":"rsmsg","type":"statusrequest","cid":"kk+ag9998=001tc000","ss":[{"sci":"s0023","n":"status"}],"mid":"2e4455e3-7f29-48d8-a430-125b930a5ef1","ntsoid":"","xnid":""}

   8) RSMP::SchemaError
      Could not send commandrequest because schema validation failed: /arg/0/cci, enum, , /arg/1/cci, enum, , /arg/2/cci, enum, {"mtype":"rsmsg","type":"commandrequest","cid":"kk+ag9998=001tc000","arg":[{"cci":"m0014","co":"setcommands","n":"securitycode","v":"testcode2"},{"cci":"m0014","co":"setcommands","n":"status","v":"1-12"},{"cci":"m0014","co":"setcommands","n":"plan","v":"1"}],"mid":"b81630c9-349e-4120-a845-efa03d94ab77","ntsoid":"","xnid":""}

   9) RSMP::SchemaError
      Could not send statusrequest because schema validation failed: /ss/0/sci, enum, {"mtype":"rsmsg","type":"statusrequest","cid":"kk+ag9998=001tc000","ss":[{"sci":"s0023","n":"status"}],"mid":"a3875238-15dc-4076-8753-1bedf041eccd","ntsoid":"","xnid":""}

  10) RSMP::SchemaError
      Could not send statusrequest because schema validation failed: /ss/0/sci, enum, {"mtype":"rsmsg","type":"statusrequest","cid":"kk+ag9998=001tc000","ss":[{"sci":"s0024","n":"status"}],"mid":"20625610-8e46-4e53-82f2-be9d0c4cfa7c","ntsoid":"","xnid":""}

  11) RSMP::SchemaError
      Could not send commandrequest because schema validation failed: /arg/0/cci, enum, , /arg/1/cci, enum, , /arg/2/cci, enum, {"mtype":"rsmsg","type":"commandrequest","cid":"kk+ag9998=001tc000","arg":[{"cci":"m0015","co":"setoffset","n":"securitycode","v":"testcode2"},{"cci":"m0015","co":"setoffset","n":"status","v":"255"},{"cci":"m0015","co":"setoffset","n":"plan","v":"1"}],"mid":"9ebc1534-6819-43d7-8173-a25cf36888d1","ntsoid":"","xnid":""}

  12) RSMP::SchemaError
      Could not send statusrequest because schema validation failed: /ss/0/sci, enum, {"mtype":"rsmsg","type":"statusrequest","cid":"kk+ag9998=001tc000","ss":[{"sci":"s0028","n":"status"}],"mid":"6480d643-4626-4790-99ba-749537b2e105","ntsoid":"","xnid":""}

  13) RSMP::SchemaError
      Could not send commandrequest because schema validation failed: /arg/0/cci, enum, , /arg/1/cci, enum, , /arg/2/cci, enum, {"mtype":"rsmsg","type":"commandrequest","cid":"kk+ag9998=001tc000","arg":[{"cci":"m0018","co":"setcycletime","n":"securitycode","v":"testcode2"},{"cci":"m0018","co":"setcycletime","n":"status","v":"5"},{"cci":"m0018","co":"setcycletime","n":"plan","v":"0"}],"mid":"ed316a6f-3aa7-4047-9d56-57e06ae0d49f","ntsoid":"","xnid":""}
```

**Comment by emiltin** [comment]
Hi, thank you for the reports. What equipment are you testing, and what validator configuration (yaml file) are you using? What branch/revision of the validator are you using?

**Comment by sveitech** [comment]
I am using the master branch (SHA  f26e49c).
Testing an ITC3 unit, with the following configuration (yaml) file:

```
port: 12111
sxl: tlc
intervals:
  timer: 1
  watchdog: 60
timeouts:
  watchdog: 5    # ITC-3 does not send watchdogs at all if other message are send
  acknowledgement: 5
  connect: 20
  ready: 5
  status_response: 5
  status_update: 5
  subscribe: 5
  command: 5
  command_response: 5
  alarm: 5
  disconnect: 5
  shutdown: 5
  startup_sequence: 5
  functional_position: 5
components:
  main:
    KK+AG9998=001TC000:
  signal_group:
    KK+AG9998=001SG001:
  detector_logic:
    KK+AG9998=001DL001:
    KK+AG9998=001DL002:
items:
  plans: [1,7,8]
  traffic_situations: []
  emergency_routes: [1]
  inputs: [1]
  force_input: 101
startup_sequence: 'efg'
secrets:
  security_codes:
    1: testcode1
    2: testcode2
restrict_testing:
  core_version: 3.1.2
  sxl_version: 1.0.13
skip_validation:
  - Alarm
alarm_activation:
  A0301: 152
```
