### ISSUE TITLE
Cartesio does not raise alarm on CAR_DL_001 when input 16 is activated

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_validator#486]
In PR #484, the Cartesio config was changed slightly to:
```yaml
alarm_triggers:
  A0302:      # raise alarm A0302
    input: 16   # when input 16 is activated
    component: CAR_DL_001  # raise alarm on this component
```

Note that the component is now set to CAR_DL_001 rather than CAR_DL_016.

This was done because I trimmed the configs so only 3 components of each type is listed, e.g. for detector logics DL1-3 are listed. I prefer that the alarm is raised one of those listed in the config.

But now the TLC does not correctly raise alarms:

```
Alarm A0302 is raised when input is activated - Failed: Alarm Collect 1798 timed out after 60s, reaching 0/1
```

The 'component' setting specifies on which component the alarm should be raised.. CAR_DL_001 is specified elsewhere in the config to be present. Do you know why the TLC does not raise the alarm on CAR_DL_001?
