### ISSUE TITLE
Ability to set ntsOid and xNId

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_validator#501]
I would be useful to be able to set `ntsOid` and `xNId` in the validator since it's still a part of the spec. 

We've observed a potential bug in a controller regarding the use of these and it would be good to pinpoint the problem.

**Comment by emiltin** [comment]
This is already possible. It's configured as part of the main component:

```yaml
components:
  main:
    TC:
      ntsOId: KK+AG9998=001TC000
```

If this is set, it's used to set the ntsOId in outgoing messages. If left out, the empty string "" is currently used.
